services:
  api:
    build:
      context: ./backend
    container_name: dev-api
    env_file:
      - ./backend/.env
    environment:
      PYTHONPATH: /app
      ENV: dev
      FRONTEND_PREVIEW: "http://localhost:5173"
      FRONTEND_PRODUCTION: "http://localhost:5173"
      DOMAIN: "http://localhost:5173"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload


