#fly.toml file 
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'fitrequest'
primary_region = 'lhr'

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[http_service.checks]]
  interval = "10s"
  timeout = "2s"
  method = "GET"
  path = "/health"
  grace_period = "60s"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[deploy]
  release_command = "bash -lc 'alembic upgrade head'"