"""linked my tables

Revision ID: 94d58650caed
Revises: c4a9f886b10c
Create Date: 2025-04-13 11:40:18.795432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94d58650caed'
down_revision: Union[str, None] = 'c4a9f886b10c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('FullName', sa.String(length=100), nullable=False),
    sa.Column('Age', sa.Integer(), nullable=True),
    sa.Column('HeightCM', sa.Integer(), nullable=True),
    sa.Column('WeightKG', sa.Integer(), nullable=True),
    sa.Column('FitnessLevel', sa.String(length=100), nullable=True),
    sa.Column('Goal', sa.String(length=200), nullable=True),
    sa.Column('InjuriesOrLimitations', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['users.ID'], ),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('UserID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
