"""Make WorkoutID nullable

Revision ID: cdc46b99ed2d
Revises: 568887abbc81
Create Date: 2025-07-19 17:49:05.024018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdc46b99ed2d'
down_revision: Union[str, None] = '568887abbc81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_workout_requests', 'WorkoutID',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_workout_requests', 'WorkoutID',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
